# Generated by Django 4.2.3 on 2025-05-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costumer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='costumer',
            name='last_name',
        ),
    ]
