# Generated by Django 4.2.3 on 2025-05-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_freelancer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='connected_costumers',
        ),
        migrations.AddField(
            model_name='costumer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('rather_not_say', 'rather not say')], default='rather_not_say', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='costumer',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='costumer',
            name='surname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
