# Generated by Django 4.2.3 on 2025-05-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_freelancer_employee_freelancerbusinessapply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancerbusinessapply',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('canceled', 'Canceled')], default='pending', max_length=15),
        ),
    ]
