# Generated by Django 4.2.3 on 2025-05-23 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_service_gender'),
        ('onboarding', '0006_alter_freelancerbusinessapply_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freelancer',
            name='employee',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freelancer', to='business.employee'),
        ),
    ]
