# Generated by Django 4.2.3 on 2025-08-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0007_alter_freelancer_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='costumer',
            name='routine_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
