from django.urls import path
from onboarding import views as onboarding_views

app_name = "onboarding"

costumer_patterns = [
    path(
        "costumer/create/",
        onboarding_views.CostumerCreateView.as_view(),
        name="costumer_create"
    ),
    path(
        "costumer/detail/",
        onboarding_views.CostumerDetailView.as_view(),
        name="costumer_create"
    ),
    path(
        "costumer/<uuid:uid>/edit/",
        onboarding_views.CostumerUpdateView.as_view(),
        name="costumer_update",
    ),
    path(
        "costumer/delete/",
        onboarding_views.CostumerDeleteView.as_view(),
        name="costumer_delete",
    ),
]

freelancer_patterns = [
    path(
        "freelancer/create/",
        onboarding_views.FreelancerCreateView.as_view(),
        name="freelancer_create",
    ),
    path(
        "freelancer/<uuid:uid>/edit/",
        onboarding_views.FreelancerUpdateView.as_view(),
        name="freelancer_update",
    ),
    path(
        "freelancer/detail/",
        onboarding_views.FreelancerDetailView.as_view(),
        name="freelancer_detail",
    ),
    path(
        "freelancer/detail/<uuid:uid>/",
        onboarding_views.FreelancerDetailWithUidView.as_view(),
        name="freelancer_detail",
    ),
    path(
        "freelancer/delete/",
        onboarding_views.FreelancerDeleteView.as_view(),
        name="freelancer_delete",
    ),
    path(
        "freelancer/freelancer-to-employee/",
        onboarding_views.FreelancerToEmployeeView.as_view(),
        name="employee_create",
    ),
    path(
        "freelancer/apply/",
        onboarding_views.FreelancerApplyView.as_view(),
        name="freelancer_apply",
    ),
    path(
        "freelancer/applies/<uuid:freelancer_uid>/",
        onboarding_views.FreelancerApplyListView.as_view(),
        name="freelancer_apply_list",
    ),
    path(
        "freelancer/applies/business/<uuid:business_uid>/",
        onboarding_views.FreelancerApplyBusinessListView.as_view(),
        name="freelancer_apply_business_list",
    ),
    path(
        "freelancer/apply/<uuid:uid>/edit/",
        onboarding_views.FreelancerApplyUpdateView.as_view(),
        name="freelancer_apply_update",
    ),
    path(
        "freelancer/apply/<uuid:uid>/delete/",
        onboarding_views.FreelancerApplyDeleteView.as_view(),
        name="freelancer_apply_delete",
    ),
    path(
        "freelancer/leave/",
        onboarding_views.FreelancerLeaveView.as_view(),
        name="freelancer_leave",
    ),
]

business_patterns = [

    path(
        "business/create/",
        onboarding_views.BusinessCreateView.as_view(),
        name="business_create",
    ),
    path(
        "my_business/",
        onboarding_views.MyBusinessView.as_view(),
        name="my_business",
    ),
    path(
        "business/<uuid:uid>/edit/",
        onboarding_views.BusinessUpdateView.as_view(),
        name="business_update",
    ),
    path(
        "business/delete/<uuid:uid>/",
        onboarding_views.BusinessDeleteView.as_view(),
        name="business_delete",
    ),
    path(
        "add/working_hours/",
        onboarding_views.WorkingHoursCreateView.as_view(),
        name="working_hours_create",
    ),
    path(
        "add/breaking_hours/",
        onboarding_views.BreakingHoursCreateView.as_view(),
        name="breaking_hours_create",
    ),
    path(
        "remove/working_hours/",
        onboarding_views.WorkingHoursDeleteView.as_view(),
        name="working_hours_delete",
    ),
    path(
        "remove/breaking_hours/",
        onboarding_views.BreakingHoursDeleteView.as_view(),
        name="breaking_hours_delete",
    ),
    path(
        "add/social/",
        onboarding_views.SocialCreateView.as_view(),
        name="social_create",
    ),
    path(
        "remove/social/<uuid:uid>/",
        onboarding_views.SocialDeleteView.as_view(),
        name="social_delete",
    ),
    path(
        "upload/image/",
        onboarding_views.UploadImageView.as_view(),
        name="upload_image",
    ),
    path(
        "image/delete/<uuid:uid>/",
        onboarding_views.DeleteImageView.as_view(),
        name="delete_image",
    ),
    path(
        "video/upload/",
        onboarding_views.UploadVideoView.as_view(),
        name="upload_video",
    ),
    path(
        "video/delete/<uuid:uid>/",
        onboarding_views.DeleteVideoView.as_view(),
        name="delete_video",
    ),
    path(
        "service/create/",
        onboarding_views.ServiceCreateView.as_view(),
        name="service_create",
    ),
    path(
        "service/edit/<uuid:uid>/",
        onboarding_views.ServiceUpdateView.as_view(),
        name="service_update",
    ),
    path(
        "upload/image/service/",
        onboarding_views.UploadImageServiceView.as_view(),
        name="upload_image_service",
    ),
    path(
        "add/working_hours/service/",
        onboarding_views.WorkingHoursCreateServiceView.as_view(),
        name="working_hours_create",
    ),
    path(
        "service/delete/<uuid:uid>/",
        onboarding_views.ServiceDeleteView.as_view(),
        name="service_delete",
    ),

    path(
        "employee/create/",
        onboarding_views.EmployeeCreateView.as_view(),
        name="employee_create",
    ),
    path(
        "employee/<uuid:uid>/edit/",
        onboarding_views.EmployeeUpdateView.as_view(),
        name="employee_update",
    ),
    path(
        "employee/<uuid:uid>/delete/",
        onboarding_views.EmployeeDeleteView.as_view(),
        name="employee_delete",
    ),
    path(
        "add/working_hours/employee/",
        onboarding_views.WorkingHoursCreateEmployeeView.as_view(),
        name="working_hours_create_employee",
    ),
]

urlpatterns = costumer_patterns + freelancer_patterns + business_patterns