# Generated by Django 4.2.3 on 2025-01-20 09:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostumNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uid')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
                ('notification_type', models.CharField(blank=True, choices=[('COSTUM', 'COSTUM'), ('NEW_MESSAGE', 'New message')], max_length=255, null=True, verbose_name='notification_type')),
                ('external_link', models.URLField(blank=True, help_text='The link that this notification should take the user to.', null=True, verbose_name='external_link')),
                ('object_type', models.CharField(blank=True, choices=[('COSTUM', 'COSTUM'), ('NEW_MESSAGE', 'New message')], help_text='The type of the object that this notification is related to. eg: beat, shop, ...', max_length=255, null=True, verbose_name='related_object_type')),
                ('object_uid', models.CharField(blank=True, help_text='The uid of the object that this notification is related to. eg: beat_uid, shop_uid, ...', max_length=255, null=True, verbose_name='related_object_uid')),
                ('object_name', models.CharField(blank=True, help_text='The name of the object that this notification is related to.', max_length=255, null=True, verbose_name='related_object_name')),
                ('genre', models.CharField(blank=True, help_text='The genre that this notification is related to.', max_length=255, null=True, verbose_name='genre')),
                ('rich_text', models.TextField(blank=True, help_text='The rich text that this notification should display.', null=True, verbose_name='rich_text')),
                ('preview_image', models.ImageField(blank=True, help_text='The image that this notification should display.', null=True, upload_to='', verbose_name='preview_image')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent_at')),
                ('is_sent', models.BooleanField(default=False, verbose_name='is_sent')),
                ('take_to_questionnaire', models.BooleanField(default=False, help_text='If true, the notification will take the user to the questionnaire screen.', verbose_name='take to questionnaire')),
                ('is_app_update', models.BooleanField(default=False, help_text='If true, the notification will be considered as an app update notification.', verbose_name='is_app_update')),
            ],
        ),
        migrations.CreateModel(
            name='NotificationObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='uid')),
                ('push_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='push_id')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('body', models.TextField(blank=True, null=True, verbose_name='body')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='data')),
                ('notification_type', models.CharField(blank=True, choices=[('COSTUM', 'COSTUM'), ('NEW_MESSAGE', 'New message')], max_length=255, null=True, verbose_name='notification_type')),
                ('is_sent', models.BooleanField(default=False, verbose_name='is_sent')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent_at')),
                ('error', models.TextField(blank=True, null=True, verbose_name='error')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read_at')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
