# Generated by Django 4.2.3 on 2025-05-02 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costumnotification',
            name='object_type',
            field=models.CharField(blank=True, choices=[('COSTUM', 'COSTUM'), ('NEW_MESSAGE', 'New message')], help_text='The type of the object that this notification is related to. eg:', max_length=255, null=True, verbose_name='related_object_type'),
        ),
        migrations.AlterField(
            model_name='costumnotification',
            name='object_uid',
            field=models.CharField(blank=True, help_text='The uid of the object that this notification is related to. eg: ', max_length=255, null=True, verbose_name='related_object_uid'),
        ),
    ]
