# Generated by Django 4.2.3 on 2025-05-05 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_costumnotification_object_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationobject',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('COSTUM', 'COSTUM'), ('NEW_MESSAGE', 'New message'), ('BOOKING_CREATED', 'BOOKING_CREATED')], max_length=255, null=True, verbose_name='notification_type'),
        ),
    ]
