# Generated by Django 4.2.3 on 2025-05-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationobject_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationobject',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('COSTUM', 'COSTUM'), ('NEW_MESSAGE', 'New message'), ('BOOKING_CREATED', 'BOOKING_CREATED'), ('BOOKING_REMINDER', 'BOOKING_REMINDER')], max_length=255, null=True, verbose_name='notification_type'),
        ),
    ]
