# Generated by Django 4.2.3 on 2025-08-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notificationobject_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationobject',
            name='notification_type',
            field=models.CharField(blank=True, choices=[('COSTUM', 'COSTUM'), ('NEW_MESSAGE', 'New message'), ('BOOKING_CREATED', 'BOOKING_CREATED'), ('BOOKING_REMINDER', 'BOOKING_REMINDER'), ('BOOKING_UPDATED', 'BOOKING_UPDATED'), ('BOOKING_CANCELLED', 'BOOKING_CANCELLED'), ('APPLY', 'APPLY'), ('APPLY_RESPONSE', 'APPLY_RESPONSE'), ('CLIENT_INVITATION', 'CLIENT_INVITATION')], max_length=255, null=True, verbose_name='notification_type'),
        ),
    ]
