# Generated by Django 4.2.3 on 2025-10-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_alter_notificationobject_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationobject',
            name='normalized_id',
            field=models.TextField(blank=True, help_text='A unique identifier for this notification to prevent duplicates.', max_length=255, null=True, verbose_name='normalized_id'),
        ),
        migrations.AddIndex(
            model_name='notificationobject',
            index=models.Index(fields=['user', 'normalized_id'], name='notificatio_user_id_f96ba7_idx'),
        ),
    ]
