# Generated by Django 4.2.3 on 2025-05-02 11:25

import core.models
import core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to=core.models.safe_file_path, validators=[core.validators.validate_file_size], verbose_name='Video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Gallery',
                'verbose_name_plural': 'Video Galleries',
            },
        ),
        migrations.AddField(
            model_name='business',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='business.videogallery'),
        ),
    ]
