# Generated by Django 4.2.3 on 2025-05-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_service_employee_userbusinesbooking_empoloyee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='working_hours',
            field=models.ManyToManyField(blank=True, related_name='employees', to='business.workinghours'),
        ),
    ]
