# Generated by Django 4.2.3 on 2025-05-05 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_employee_working_hours'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbusinesbooking',
            old_name='empoloyee',
            new_name='employee',
        ),
    ]
