# Generated by Django 4.2.3 on 2025-05-05 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_rename_empoloyee_userbusinesbooking_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusinesbooking',
            name='day_of_week',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='monday', max_length=9),
        ),
        migrations.AlterField(
            model_name='userbusinesbooking',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='userbusinesbooking',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
