# Generated by Django 4.2.3 on 2025-05-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_userbusinesbooking_day_of_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusinesbooking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbusinesbooking',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbusinesbooking',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
