# Generated by Django 4.2.3 on 2025-05-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_userbusinesbooking_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusinesbooking',
            name='was_user_reminded',
            field=models.BooleanField(default=False, help_text='Was remind notification sent to user'),
        ),
    ]
