# Generated by Django 4.2.3 on 2025-05-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_employee_avatar_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
