# Generated by Django 4.2.3 on 2025-05-22 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_business_latitude_business_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], default='other', max_length=255, null=True),
        ),
    ]
