# Generated by Django 4.2.3 on 2025-05-23 11:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_service_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNotificationSenderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('booking_email', models.BooleanField(default=True, help_text='Send Booking email to costumers')),
                ('booking_notification', models.BooleanField(default=True, help_text='Send Booking notification to costumers')),
                ('reminder_email', models.BooleanField(default=True, help_text='Send Reminder email to costumers')),
                ('reminder_notification', models.BooleanField(default=True, help_text='Send Reminder notification to costumers')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='business.business')),
            ],
            options={
                'verbose_name': 'Business Notification Settings',
                'verbose_name_plural': 'Business Notification Settings',
            },
        ),
    ]
