# Generated by Django 4.2.3 on 2025-05-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_businessnotificationsendersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbusinesbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=255),
        ),
    ]
