# Generated by Django 4.2.3 on 2025-06-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_alter_userbusinesbooking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='note_to_clients',
            field=models.TextField(blank=True, null=True),
        ),
    ]
