# Generated by Django 4.2.3 on 2025-06-23 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_business_note_to_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='GBP', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='duration',
            field=models.DurationField(blank=True, help_text='Duration of the service in HH:MM:SS format', null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
