# Generated by Django 4.2.3 on 2025-06-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_servicecategory_currency_servicecategory_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='services_categories', to='business.servicecategory'),
        ),
    ]
