# Generated by Django 4.2.3 on 2025-06-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_service_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmedia',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
