# Generated by Django 4.2.3 on 2025-06-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_alter_service_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
    ]
