# Generated by Django 4.2.3 on 2025-06-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0021_remove_service_description_remove_service_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='employees_services', to='business.service'),
        ),
    ]
