# Generated by Django 4.2.3 on 2025-07-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0023_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='collaborated_business',
            field=models.TextField(blank=True, null=True),
        ),
    ]
