# Generated by Django 4.2.3 on 2025-07-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_alter_socialmedia_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='breaking_hours',
            field=models.ManyToManyField(blank=True, related_name='businesses_breaking_hours', to='business.workinghours'),
        ),
    ]
