# Generated by Django 4.2.3 on 2025-07-10 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_business_breaking_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='apply_for_weeks',
            field=models.CharField(blank=True, choices=[('this_week_only', 'This Week Only'), ('this_week_and_next', 'This Week and Next'), ('all_weeks', 'All Weeks')], default='all_weeks', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='time_step',
            field=models.DurationField(blank=True, help_text='Time step for bookings in HH:MM:SS format', null=True),
        ),
    ]
