# Generated by Django 4.2.3 on 2025-07-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0027_business_apply_for_weeks_business_time_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
