# Generated by Django 4.2.3 on 2025-07-19 12:23

from django.db import migrations
from business import enums as business_enums


def load_old_user_business_bookings(apps, schema_editor):
    try:
        User = apps.get_model('auth', 'User')
        Booking = apps.get_model('business', 'Booking')
        BusinessClient = apps.get_model('business', 'BusinessClient')

        # Fetch all users who are business clients
        business_clients = BusinessClient.objects.all()

        for client in business_clients:
            user = User.objects.filter(id=client.user_id).first()
            if user:
                # Create a booking for each business client
                Booking.objects.create(
                    user=user,
                    business_client=client,
                    status=business_enums.BookingStatusChoices.CONFIRMED,
                )
    except Exception as e:
        print(f"Error loading old user business bookings: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_businessclient'),
    ]

    operations = [
        migrations.RunPython(
            load_old_user_business_bookings, reverse_code=migrations.RunPython.noop
        ),
    ]
