# Generated by Django 4.2.3 on 2025-07-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_auto_20250719_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusinesbooking',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='category_bookings', to='business.servicecategory'),
        ),
    ]
