# Generated by Django 4.2.3 on 2025-07-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_userbusinesbooking_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusinesbooking',
            name='cancel_reason',
            field=models.TextField(blank=True, help_text='Reason for cancellation if the booking is cancelled', null=True),
        ),
    ]
