# Generated by Django 4.2.3 on 2025-07-29 10:43

import core.models
import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_userbusinesbooking_cancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=core.models.safe_file_path, validators=[core.validators.validate_file_size], verbose_name='Image'),
        ),
    ]
