# Generated by Django 4.2.3 on 2025-08-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0033_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Is this image the main image for the business?'),
        ),
    ]
