# Generated by Django 4.2.3 on 2025-08-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0034_gallery_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('ALL', 'Albanian Lek')], default='USD', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='servicecategory',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('ALL', 'Albanian Lek')], default='GBP', max_length=3, null=True),
        ),
    ]
