# Generated by Django 4.2.3 on 2025-08-07 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_alter_businessclient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessclient',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=255),
        ),
    ]
