# Generated by Django 4.2.3 on 2025-08-12 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0038_alter_businessclient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='collaboration_address',
            field=models.CharField(blank=True, help_text='Address for collaboration with other businesses', max_length=255, null=True),
        ),
    ]
