# Generated by Django 4.2.3 on 2025-08-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0039_business_collaboration_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='description_sq',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='name_sq',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: _populate_servicecategory_new_fields(apps, schema_editor),
            reverse_code=lambda apps, schema_editor: _revert_servicecategory_new_fields(apps, schema_editor),
        ),
    ]


def _populate_servicecategory_new_fields(apps, schema_editor):
    ServiceCategory = apps.get_model('business', 'ServiceCategory')
    # Iterate with iterator() to avoid loading all at once if large
    for sc in ServiceCategory.objects.all().iterator():
        changed_fields = []
        # Copy existing name into both language variants if empty
        if getattr(sc, 'name_en', None) in (None, ''):
            sc.name_en = sc.name
            changed_fields.append('name_en')
        if getattr(sc, 'name_sq', None) in (None, ''):
            sc.name_sq = sc.name
            changed_fields.append('name_sq')
        # Copy existing description into both language variants if present and empty
        if sc.description:
            if getattr(sc, 'description_en', None) in (None, ''):
                sc.description_en = sc.description
                changed_fields.append('description_en')
            if getattr(sc, 'description_sq', None) in (None, ''):
                sc.description_sq = sc.description
                changed_fields.append('description_sq')
        if changed_fields:
            sc.save(update_fields=changed_fields)


def _revert_servicecategory_new_fields(apps, schema_editor):
    """Best-effort reverse: if original fields are blank, restore from *_en."""
    ServiceCategory = apps.get_model('business', 'ServiceCategory')
    for sc in ServiceCategory.objects.all().iterator():
        changed_fields = []
        if (sc.name in (None, '')) and getattr(sc, 'name_en', None):
            sc.name = sc.name_en
            changed_fields.append('name')
        if (sc.description in (None, '')) and getattr(sc, 'description_en', None):
            sc.description = sc.description_en
            changed_fields.append('description')
        if changed_fields:
            sc.save(update_fields=changed_fields)
