# Generated by Django 4.2.3 on 2025-08-13 08:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0040_servicecategory_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='address_on',
            field=models.BooleanField(default=True, help_text='Is address enabled?'),
        ),
        migrations.AddField(
            model_name='business',
            name='collaboration_address_on',
            field=models.BooleanField(default=False, help_text='Is collaboration address enabled?'),
        ),
        migrations.AddField(
            model_name='business',
            name='collaboration_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Collaboration Location'),
        ),
    ]
