# Generated by Django 4.2.3 on 2025-08-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0041_business_address_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbusinesbooking',
            name='was_user_reminded_daily',
            field=models.BooleanField(default=False, help_text='Was daily remind notification sent to user'),
        ),
    ]
