# Generated by Django 4.2.3 on 2025-12-09 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0042_userbusinesbooking_was_user_reminded_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='service_type',
            field=models.CharField(choices=[('hair', 'Hair'), ('body', 'Body'), ('doctor', 'Doctor'), ('makeup', 'Makeup'), ('massage', 'Massage'), ('nails', 'Nails'), ('physiotherapist', 'Physiotherapist'), ('personal_trainer', 'Personal Trainer')], default='hair', help_text='Type of service this category represents', max_length=255),
        ),
    ]
