# Generated by Django 4.2.3 on 2025-12-09 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0043_servicecategory_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
