# Generated by Django 4.2.3 on 2025-12-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0044_business_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='apply_for_weeks_date',
            field=models.DateField(blank=True, help_text="Specific date to apply the 'apply for weeks' setting from", null=True),
        ),
    ]
