# Generated by Django 4.2.3 on 2025-04-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='gmc_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='GMC number'),
        ),
    ]
