# Generated by Django 4.2.3 on 2025-04-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_bio_user_gmc_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='license_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='License number'),
        ),
    ]
