# Generated by Django 4.2.3 on 2025-05-01 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_user_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gmc_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='license_number',
        ),
        migrations.RemoveField(
            model_name='user',
            name='title',
        ),
    ]
