# Generated by Django 4.2.3 on 2025-05-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_user_bio_remove_user_gmc_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='send_email_notification',
            field=models.BooleanField(default=True, verbose_name='Send email notifications'),
        ),
    ]
