# Generated by Django 4.2.3 on 2025-05-08 11:13

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_user_send_email_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'email_already_used'}, max_length=255, null=True, unique=True, validators=[core.validators.email_validator], verbose_name='Email'),
        ),
    ]
