# Generated by Django 4.2.3 on 2025-05-15 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsettings',
            name='booking_email',
            field=models.BooleanField(default=True, verbose_name='Get booking email'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='booking_notification',
            field=models.BooleanField(default=True, verbose_name='Get booking notification'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='reminder_email',
            field=models.BooleanField(default=True, verbose_name='Get reminder email'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='reminder_notification',
            field=models.BooleanField(default=True, verbose_name='Get reminder notification'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='updates_and_promotions_email',
            field=models.BooleanField(default=True, verbose_name='Get Updated and promotions email'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='updates_and_promotions_notification',
            field=models.BooleanField(default=True, verbose_name='GEt Updated and promotions notification'),
        ),
    ]
