# Generated by Django 4.2.3 on 2025-05-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_usernotificationsettings_booking_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsettings',
            name='apply_notification',
            field=models.BooleanField(default=True, verbose_name='Apply to business notification'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='apply_response_notification',
            field=models.BooleanField(default=True, verbose_name='Apply response to business notification'),
        ),
    ]
