# Generated by Django 4.2.3 on 2025-05-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_usernotificationsettings_apply_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsettings',
            name='booking_cancellation_email',
            field=models.BooleanField(default=True, verbose_name='Get booking cancellation email'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='booking_cancellation_notification',
            field=models.BooleanField(default=True, verbose_name='Get booking cancellation notification'),
        ),
    ]
