# Generated by Django 4.2.3 on 2025-06-24 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_usernotificationsettings_booking_cancellation_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='chosen_role',
            field=models.CharField(blank=True, choices=[('BUSINESS', 'BUSINESS'), ('CUSTOMER', 'CUSTOMER'), ('FREELANCER', 'FREELANCER')], default=None, max_length=64, null=True, verbose_name='Chosen role'),
        ),
    ]
