# Generated by Django 4.2.3 on 2025-07-31 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_userdevice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdevice',
            name='device_id',
            field=models.CharField(max_length=255, verbose_name='Device ID'),
        ),
    ]
