# Generated by Django 4.2.3 on 2025-08-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_userdevice_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Avatar ID'),
        ),
    ]
