# Generated by Django 4.2.3 on 2025-10-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_user_avatar_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Europe/London', max_length=64, verbose_name='Timezone'),
        ),
    ]
