# Generated by Django 4.2.3 on 2025-11-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang_code',
            field=models.CharField(default='en', max_length=8, verbose_name='Language code'),
        ),
    ]
