# Generated by Django 4.2.3 on 2025-12-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_user_lang_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsettings',
            name='apply_notification_email',
            field=models.BooleanField(default=True, verbose_name='Apply to business email'),
        ),
        migrations.AddField(
            model_name='usernotificationsettings',
            name='apply_response_notification_email',
            field=models.BooleanField(default=True, verbose_name='Apply response to business email'),
        ),
    ]
