# Generated by Django 4.2.3 on 2025-02-03 10:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('terms_and_conditions', models.URLField(blank=True, null=True, verbose_name='Terms and Conditions')),
                ('privacy_policy', models.URLField(blank=True, null=True, verbose_name='Privacy Policy')),
                ('cookie_policy', models.URLField(blank=True, null=True, verbose_name='Cookie Policy')),
            ],
            options={
                'verbose_name': 'Policy Link',
                'verbose_name_plural': 'Policy Links',
            },
        ),
    ]
