# Generated by Django 4.2.3 on 2025-05-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_rating_reply_to_alter_rating_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='service',
            new_name='business',
        ),
    ]
