# Generated by Django 4.2.3 on 2025-05-02 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_videogallery_business_videos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0003_rename_service_rating_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBusinessSave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Business Save',
                'verbose_name_plural': 'User Business Saves',
                'unique_together': {('user', 'business')},
            },
        ),
        migrations.CreateModel(
            name='UserBusinessFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='business.business')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Business Favorite',
                'verbose_name_plural': 'User Business Favorites',
                'unique_together': {('user', 'business')},
            },
        ),
    ]
