# Generated by Django 4.2.3 on 2025-05-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_service_employee_userbusinesbooking_empoloyee_and_more'),
        ('rating', '0004_userbusinesssave_userbusinessfavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='business.userbusinesbooking'),
        ),
    ]
