# Generated by Django 4.2.3 on 2025-05-05 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_service_employee_userbusinesbooking_empoloyee_and_more'),
        ('rating', '0005_rating_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='booking',
        ),
        migrations.AddField(
            model_name='rating',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='business.employee'),
        ),
    ]
