# Generated by Django 4.2.3 on 2025-05-06 13:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_userbusinesbooking_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rating', '0007_alter_rating_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmployeeFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='business.employee')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Employee Favorite',
                'verbose_name_plural': 'User Employee Favorites',
                'unique_together': {('user', 'employee')},
            },
        ),
    ]
