# Generated by Django 4.2.3 on 2025-07-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_service_name'),
        ('rating', '0008_useremployeefavorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='business.userbusinesbooking'),
        ),
    ]
